version: 1.1.0.{build}
environment:
  Major: 1
  Minor: 1
  Patch: 0
configuration: Release
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: minimal
test: off
artifacts:
- path: '.\Build\*.nupkg'
deploy:
- provider: Environment
  name: MyGet